# Generated by Django 4.2.10 on 2024-06-06 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='tasks',
        ),
        migrations.AddField(
            model_name='person',
            name='name',
            field=models.CharField(blank=True, max_length=20, verbose_name='User Name'),
        ),
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.person'),
        ),
    ]
