# Generated by Django 4.2.13 on 2024-06-07 15:51

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_person_tasks_person_name_task_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='name',
        ),
        migrations.AddField(
            model_name='person',
            name='User Name',
            field=models.CharField(blank=True, max_length=20, verbose_name=django.contrib.auth.models.User),
        ),
    ]
