# Generated by Django 4.2.13 on 2024-06-20 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_task_date_alter_task_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
